<?php

use Illuminate\Database\Seeder;

class MedianHousePricesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('median-house-prices')->delete();

        \DB::table('median-house-prices')->insert(array(
            0 =>
            array(
                'date' => 'Sep-2003',
                'median_price_sydney' => 480.0,
                'median_price_nsw' => 247.3,
                'median_price_melbourne' => 295.0,
                'median_price_vic' => 176.0,
                'median_price_brisbane' => 269.0,
                'median_price_qld' => 197.0,
                'median_price_adelaide' => 235.0,
                'median_price_sa' => 150.0,
                'median_price_perth' => 236.0,
                'median_price_wa' => 160.0,
                'median_price_hobart' => 165.0,
                'median_price_tas' => 125.0,
                'median_price_darwin' => 214.0,
                'median_price_nt' => 195.0,
                'median_price_canberra' => 360.0,
            ),
            1 =>
            array(
                'date' => 'Dec-2003',
                'median_price_sydney' => 520.0,
                'median_price_nsw' => 255.0,
                'median_price_melbourne' => 320.0,
                'median_price_vic' => 185.0,
                'median_price_brisbane' => 296.4,
                'median_price_qld' => 205.0,
                'median_price_adelaide' => 247.5,
                'median_price_sa' => 162.0,
                'median_price_perth' => 250.0,
                'median_price_wa' => 164.0,
                'median_price_hobart' => 182.3,
                'median_price_tas' => 139.3,
                'median_price_darwin' => 226.0,
                'median_price_nt' => 204.5,
                'median_price_canberra' => 375.0,
            ),
            2 =>
            array(
                'date' => 'Mar-2004',
                'median_price_sydney' => 523.0,
                'median_price_nsw' => 265.0,
                'median_price_melbourne' => 305.0,
                'median_price_vic' => 190.0,
                'median_price_brisbane' => 302.7,
                'median_price_qld' => 224.0,
                'median_price_adelaide' => 250.0,
                'median_price_sa' => 166.6,
                'median_price_perth' => 255.0,
                'median_price_wa' => 178.0,
                'median_price_hobart' => 200.0,
                'median_price_tas' => 156.0,
                'median_price_darwin' => 239.5,
                'median_price_nt' => 217.8,
                'median_price_canberra' => 375.0,
            ),
            3 =>
            array(
                'date' => 'Jun-2004',
                'median_price_sydney' => 498.0,
                'median_price_nsw' => 270.0,
                'median_price_melbourne' => 307.5,
                'median_price_vic' => 195.0,
                'median_price_brisbane' => 305.0,
                'median_price_qld' => 235.0,
                'median_price_adelaide' => 257.5,
                'median_price_sa' => 169.0,
                'median_price_perth' => 262.0,
                'median_price_wa' => 178.0,
                'median_price_hobart' => 225.0,
                'median_price_tas' => 156.0,
                'median_price_darwin' => 248.8,
                'median_price_nt' => 215.0,
                'median_price_canberra' => 375.0,
            ),
            4 =>
            array(
                'date' => 'Sep-2004',
                'median_price_sydney' => 500.0,
                'median_price_nsw' => 275.0,
                'median_price_melbourne' => 302.0,
                'median_price_vic' => 195.0,
                'median_price_brisbane' => 305.0,
                'median_price_qld' => 244.0,
                'median_price_adelaide' => 261.0,
                'median_price_sa' => 175.0,
                'median_price_perth' => 259.0,
                'median_price_wa' => 185.0,
                'median_price_hobart' => 230.0,
                'median_price_tas' => 160.0,
                'median_price_darwin' => 245.0,
                'median_price_nt' => 227.5,
                'median_price_canberra' => 352.5,
            ),
            5 =>
            array(
                'date' => 'Dec-2004',
                'median_price_sydney' => 515.0,
                'median_price_nsw' => 278.0,
                'median_price_melbourne' => 321.0,
                'median_price_vic' => 205.0,
                'median_price_brisbane' => 310.0,
                'median_price_qld' => 255.0,
                'median_price_adelaide' => 270.0,
                'median_price_sa' => 182.0,
                'median_price_perth' => 280.0,
                'median_price_wa' => 199.8,
                'median_price_hobart' => 237.3,
                'median_price_tas' => 166.5,
                'median_price_darwin' => 259.0,
                'median_price_nt' => 227.0,
                'median_price_canberra' => 372.0,
            ),
            6 =>
            array(
                'date' => 'Mar-2005',
                'median_price_sydney' => 486.0,
                'median_price_nsw' => 280.0,
                'median_price_melbourne' => 310.0,
                'median_price_vic' => 210.0,
                'median_price_brisbane' => 312.0,
                'median_price_qld' => 270.0,
                'median_price_adelaide' => 270.0,
                'median_price_sa' => 187.0,
                'median_price_perth' => 290.0,
                'median_price_wa' => 225.0,
                'median_price_hobart' => 240.0,
                'median_price_tas' => 179.0,
                'median_price_darwin' => 275.0,
                'median_price_nt' => 231.0,
                'median_price_canberra' => 374.7,
            ),
            7 =>
            array(
                'date' => 'Jun-2005',
                'median_price_sydney' => 500.0,
                'median_price_nsw' => 280.0,
                'median_price_melbourne' => 320.0,
                'median_price_vic' => 205.0,
                'median_price_brisbane' => 312.0,
                'median_price_qld' => 280.0,
                'median_price_adelaide' => 271.0,
                'median_price_sa' => 192.0,
                'median_price_perth' => 300.0,
                'median_price_wa' => 230.0,
                'median_price_hobart' => 250.0,
                'median_price_tas' => 178.3,
                'median_price_darwin' => 280.0,
                'median_price_nt' => 230.0,
                'median_price_canberra' => 373.5,
            ),
            8 =>
            array(
                'date' => 'Sep-2005',
                'median_price_sydney' => 490.0,
                'median_price_nsw' => 280.0,
                'median_price_melbourne' => 320.0,
                'median_price_vic' => 210.0,
                'median_price_brisbane' => 314.9,
                'median_price_qld' => 285.0,
                'median_price_adelaide' => 275.0,
                'median_price_sa' => 189.3,
                'median_price_perth' => 315.0,
                'median_price_wa' => 245.0,
                'median_price_hobart' => 245.0,
                'median_price_tas' => 180.0,
                'median_price_darwin' => 295.0,
                'median_price_nt' => 232.0,
                'median_price_canberra' => 365.0,
            ),
            9 =>
            array(
                'date' => 'Dec-2005',
                'median_price_sydney' => 500.0,
                'median_price_nsw' => 285.0,
                'median_price_melbourne' => 332.0,
                'median_price_vic' => 220.0,
                'median_price_brisbane' => 320.0,
                'median_price_qld' => 290.0,
                'median_price_adelaide' => 280.0,
                'median_price_sa' => 199.0,
                'median_price_perth' => 340.0,
                'median_price_wa' => 265.0,
                'median_price_hobart' => 252.5,
                'median_price_tas' => 192.0,
                'median_price_darwin' => 320.0,
                'median_price_nt' => 246.0,
                'median_price_canberra' => 387.0,
            ),
            10 =>
            array(
                'date' => 'Mar-2006',
                'median_price_sydney' => 470.0,
                'median_price_nsw' => 290.0,
                'median_price_melbourne' => 330.0,
                'median_price_vic' => 224.0,
                'median_price_brisbane' => 325.0,
                'median_price_qld' => 309.0,
                'median_price_adelaide' => 280.0,
                'median_price_sa' => 210.0,
                'median_price_perth' => 370.0,
                'median_price_wa' => 295.0,
                'median_price_hobart' => 260.0,
                'median_price_tas' => 192.0,
                'median_price_darwin' => 341.5,
                'median_price_nt' => 215.0,
                'median_price_canberra' => 385.0,
            ),
            11 =>
            array(
                'date' => 'Jun-2006',
                'median_price_sydney' => 495.0,
                'median_price_nsw' => 290.0,
                'median_price_melbourne' => 345.0,
                'median_price_vic' => 220.0,
                'median_price_brisbane' => 330.0,
                'median_price_qld' => 312.5,
                'median_price_adelaide' => 286.0,
                'median_price_sa' => 210.0,
                'median_price_perth' => 415.0,
                'median_price_wa' => 324.0,
                'median_price_hobart' => 270.0,
                'median_price_tas' => 200.0,
                'median_price_darwin' => 349.5,
                'median_price_nt' => 240.0,
                'median_price_canberra' => 399.5,
            ),
            12 =>
            array(
                'date' => 'Sep-2006',
                'median_price_sydney' => 482.0,
                'median_price_nsw' => 285.0,
                'median_price_melbourne' => 346.0,
                'median_price_vic' => 222.0,
                'median_price_brisbane' => 335.0,
                'median_price_qld' => 318.4,
                'median_price_adelaide' => 290.0,
                'median_price_sa' => 200.0,
                'median_price_perth' => 450.0,
                'median_price_wa' => 335.0,
                'median_price_hobart' => 270.0,
                'median_price_tas' => 195.0,
                'median_price_darwin' => 360.0,
                'median_price_nt' => 247.5,
                'median_price_canberra' => 413.0,
            ),
            13 =>
            array(
                'date' => 'Dec-2006',
                'median_price_sydney' => 500.0,
                'median_price_nsw' => 290.0,
                'median_price_melbourne' => 360.0,
                'median_price_vic' => 230.0,
                'median_price_brisbane' => 343.5,
                'median_price_qld' => 330.0,
                'median_price_adelaide' => 300.0,
                'median_price_sa' => 215.0,
                'median_price_perth' => 470.0,
                'median_price_wa' => 350.0,
                'median_price_hobart' => 278.0,
                'median_price_tas' => 199.0,
                'median_price_darwin' => 380.0,
                'median_price_nt' => 260.0,
                'median_price_canberra' => 420.8,
            ),
            14 =>
            array(
                'date' => 'Mar-2007',
                'median_price_sydney' => 480.0,
                'median_price_nsw' => 300.0,
                'median_price_melbourne' => 345.0,
                'median_price_vic' => 230.0,
                'median_price_brisbane' => 352.0,
                'median_price_qld' => 347.0,
                'median_price_adelaide' => 305.0,
                'median_price_sa' => 223.0,
                'median_price_perth' => 475.0,
                'median_price_wa' => 370.0,
                'median_price_hobart' => 280.0,
                'median_price_tas' => 210.0,
                'median_price_darwin' => 389.5,
                'median_price_nt' => 250.0,
                'median_price_canberra' => 430.0,
            ),
            15 =>
            array(
                'date' => 'Jun-2007',
                'median_price_sydney' => 512.3,
                'median_price_nsw' => 300.0,
                'median_price_melbourne' => 362.0,
                'median_price_vic' => 230.0,
                'median_price_brisbane' => 375.0,
                'median_price_qld' => 365.0,
                'median_price_adelaide' => 315.0,
                'median_price_sa' => 223.3,
                'median_price_perth' => 465.0,
                'median_price_wa' => 374.0,
                'median_price_hobart' => 291.5,
                'median_price_tas' => 220.0,
                'median_price_darwin' => 395.0,
                'median_price_nt' => 278.8,
                'median_price_canberra' => 445.0,
            ),
            16 =>
            array(
                'date' => 'Sep-2007',
                'median_price_sydney' => 514.0,
                'median_price_nsw' => 300.0,
                'median_price_melbourne' => 370.0,
                'median_price_vic' => 233.5,
                'median_price_brisbane' => 390.0,
                'median_price_qld' => 376.0,
                'median_price_adelaide' => 335.0,
                'median_price_sa' => 228.0,
                'median_price_perth' => 475.0,
                'median_price_wa' => 376.4,
                'median_price_hobart' => 285.0,
                'median_price_tas' => 220.0,
                'median_price_darwin' => 400.0,
                'median_price_nt' => 270.0,
                'median_price_canberra' => 460.0,
            ),
            17 =>
            array(
                'date' => 'Dec-2007',
                'median_price_sydney' => 540.0,
                'median_price_nsw' => 310.0,
                'median_price_melbourne' => 410.0,
                'median_price_vic' => 245.0,
                'median_price_brisbane' => 415.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 358.0,
                'median_price_sa' => 245.0,
                'median_price_perth' => 480.0,
                'median_price_wa' => 379.5,
                'median_price_hobart' => 310.0,
                'median_price_tas' => 230.0,
                'median_price_darwin' => 418.5,
                'median_price_nt' => 289.0,
                'median_price_canberra' => 468.0,
            ),
            18 =>
            array(
                'date' => 'Mar-2008',
                'median_price_sydney' => 495.0,
                'median_price_nsw' => 308.0,
                'median_price_melbourne' => 385.0,
                'median_price_vic' => 243.5,
                'median_price_brisbane' => 425.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 360.0,
                'median_price_sa' => 250.0,
                'median_price_perth' => 470.0,
                'median_price_wa' => 390.0,
                'median_price_hobart' => 308.5,
                'median_price_tas' => 239.5,
                'median_price_darwin' => 420.0,
                'median_price_nt' => 285.0,
                'median_price_canberra' => 470.0,
            ),
            19 =>
            array(
                'date' => 'Jun-2008',
                'median_price_sydney' => 517.0,
                'median_price_nsw' => 305.0,
                'median_price_melbourne' => 400.0,
                'median_price_vic' => 239.0,
                'median_price_brisbane' => 425.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 365.0,
                'median_price_sa' => 240.0,
                'median_price_perth' => 455.0,
                'median_price_wa' => 360.0,
                'median_price_hobart' => 305.0,
                'median_price_tas' => 230.0,
                'median_price_darwin' => 422.3,
                'median_price_nt' => 285.0,
                'median_price_canberra' => 474.0,
            ),
            20 =>
            array(
                'date' => 'Sep-2008',
                'median_price_sydney' => 482.0,
                'median_price_nsw' => 297.5,
                'median_price_melbourne' => 385.0,
                'median_price_vic' => 235.0,
                'median_price_brisbane' => 410.0,
                'median_price_qld' => 365.0,
                'median_price_adelaide' => 360.0,
                'median_price_sa' => 245.0,
                'median_price_perth' => 440.0,
                'median_price_wa' => 365.0,
                'median_price_hobart' => 292.5,
                'median_price_tas' => 235.0,
                'median_price_darwin' => 430.0,
                'median_price_nt' => 285.0,
                'median_price_canberra' => 447.0,
            ),
            21 =>
            array(
                'date' => 'Dec-2008',
                'median_price_sydney' => 468.0,
                'median_price_nsw' => 290.0,
                'median_price_melbourne' => 385.0,
                'median_price_vic' => 236.0,
                'median_price_brisbane' => 399.0,
                'median_price_qld' => 365.0,
                'median_price_adelaide' => 355.0,
                'median_price_sa' => 245.0,
                'median_price_perth' => 425.0,
                'median_price_wa' => 351.0,
                'median_price_hobart' => 300.0,
                'median_price_tas' => 225.0,
                'median_price_darwin' => 445.0,
                'median_price_nt' => 296.8,
                'median_price_canberra' => 450.0,
            ),
            22 =>
            array(
                'date' => 'Mar-2009',
                'median_price_sydney' => 448.0,
                'median_price_nsw' => 300.0,
                'median_price_melbourne' => 375.0,
                'median_price_vic' => 238.0,
                'median_price_brisbane' => 400.0,
                'median_price_qld' => 370.0,
                'median_price_adelaide' => 353.5,
                'median_price_sa' => 248.0,
                'median_price_perth' => 439.0,
                'median_price_wa' => 360.0,
                'median_price_hobart' => 296.5,
                'median_price_tas' => 235.0,
                'median_price_darwin' => 455.0,
                'median_price_nt' => 321.0,
                'median_price_canberra' => 459.5,
            ),
            23 =>
            array(
                'date' => 'Jun-2009',
                'median_price_sydney' => 490.0,
                'median_price_nsw' => 300.0,
                'median_price_melbourne' => 400.0,
                'median_price_vic' => 245.0,
                'median_price_brisbane' => 420.0,
                'median_price_qld' => 372.8,
                'median_price_adelaide' => 363.0,
                'median_price_sa' => 245.0,
                'median_price_perth' => 455.0,
                'median_price_wa' => 370.0,
                'median_price_hobart' => 310.0,
                'median_price_tas' => 240.0,
                'median_price_darwin' => 465.0,
                'median_price_nt' => 335.0,
                'median_price_canberra' => 455.0,
            ),
            24 =>
            array(
                'date' => 'Sep-2009',
                'median_price_sydney' => 500.0,
                'median_price_nsw' => 310.0,
                'median_price_melbourne' => 422.0,
                'median_price_vic' => 250.0,
                'median_price_brisbane' => 430.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 370.0,
                'median_price_sa' => 260.0,
                'median_price_perth' => 473.0,
                'median_price_wa' => 375.0,
                'median_price_hobart' => 310.1,
                'median_price_tas' => 245.0,
                'median_price_darwin' => 490.0,
                'median_price_nt' => 345.0,
                'median_price_canberra' => 456.0,
            ),
            25 =>
            array(
                'date' => 'Dec-2009',
                'median_price_sydney' => 595.0,
                'median_price_nsw' => 340.0,
                'median_price_melbourne' => 477.5,
                'median_price_vic' => 266.5,
                'median_price_brisbane' => 455.0,
                'median_price_qld' => 395.0,
                'median_price_adelaide' => 398.8,
                'median_price_sa' => 267.0,
                'median_price_perth' => 505.0,
                'median_price_wa' => 400.0,
                'median_price_hobart' => 350.0,
                'median_price_tas' => 252.3,
                'median_price_darwin' => 520.0,
                'median_price_nt' => 368.0,
                'median_price_canberra' => 509.0,
            ),
            26 =>
            array(
                'date' => 'Mar-2010',
                'median_price_sydney' => 583.0,
                'median_price_nsw' => 340.0,
                'median_price_melbourne' => 468.0,
                'median_price_vic' => 275.0,
                'median_price_brisbane' => 460.0,
                'median_price_qld' => 400.0,
                'median_price_adelaide' => 402.0,
                'median_price_sa' => 280.0,
                'median_price_perth' => 518.0,
                'median_price_wa' => 410.0,
                'median_price_hobart' => 350.5,
                'median_price_tas' => 262.0,
                'median_price_darwin' => 529.0,
                'median_price_nt' => 364.0,
                'median_price_canberra' => 530.0,
            ),
            27 =>
            array(
                'date' => 'Jun-2010',
                'median_price_sydney' => 612.5,
                'median_price_nsw' => 340.0,
                'median_price_melbourne' => 500.0,
                'median_price_vic' => 278.2,
                'median_price_brisbane' => 465.0,
                'median_price_qld' => 395.0,
                'median_price_adelaide' => 410.0,
                'median_price_sa' => 278.0,
                'median_price_perth' => 510.0,
                'median_price_wa' => 385.0,
                'median_price_hobart' => 343.8,
                'median_price_tas' => 257.0,
                'median_price_darwin' => 530.0,
                'median_price_nt' => 395.0,
                'median_price_canberra' => 516.2,
            ),
            28 =>
            array(
                'date' => 'Sep-2010',
                'median_price_sydney' => 598.0,
                'median_price_nsw' => 340.0,
                'median_price_melbourne' => 488.3,
                'median_price_vic' => 280.0,
                'median_price_brisbane' => 460.0,
                'median_price_qld' => 388.0,
                'median_price_adelaide' => 400.0,
                'median_price_sa' => 275.0,
                'median_price_perth' => 500.0,
                'median_price_wa' => 380.0,
                'median_price_hobart' => 340.0,
                'median_price_tas' => 260.0,
                'median_price_darwin' => 535.0,
                'median_price_nt' => 421.5,
                'median_price_canberra' => 530.0,
            ),
            29 =>
            array(
                'date' => 'Dec-2010',
                'median_price_sydney' => 620.0,
                'median_price_nsw' => 340.0,
                'median_price_melbourne' => 520.0,
                'median_price_vic' => 292.5,
                'median_price_brisbane' => 460.0,
                'median_price_qld' => 387.5,
                'median_price_adelaide' => 410.0,
                'median_price_sa' => 277.3,
                'median_price_perth' => 500.0,
                'median_price_wa' => 385.0,
                'median_price_hobart' => 345.0,
                'median_price_tas' => 260.0,
                'median_price_darwin' => 545.0,
                'median_price_nt' => 435.0,
                'median_price_canberra' => 534.5,
            ),
            30 =>
            array(
                'date' => 'Mar-2011',
                'median_price_sydney' => 575.0,
                'median_price_nsw' => 345.0,
                'median_price_melbourne' => 485.0,
                'median_price_vic' => 293.0,
                'median_price_brisbane' => 450.0,
                'median_price_qld' => 392.8,
                'median_price_adelaide' => 400.0,
                'median_price_sa' => 270.0,
                'median_price_perth' => 500.0,
                'median_price_wa' => 385.3,
                'median_price_hobart' => 338.0,
                'median_price_tas' => 263.9,
                'median_price_darwin' => 510.0,
                'median_price_nt' => 430.0,
                'median_price_canberra' => 530.0,
            ),
            31 =>
            array(
                'date' => 'Jun-2011',
                'median_price_sydney' => 592.0,
                'median_price_nsw' => 342.0,
                'median_price_melbourne' => 502.5,
                'median_price_vic' => 295.0,
                'median_price_brisbane' => 442.0,
                'median_price_qld' => 383.0,
                'median_price_adelaide' => 395.0,
                'median_price_sa' => 275.0,
                'median_price_perth' => 485.0,
                'median_price_wa' => 380.0,
                'median_price_hobart' => 330.0,
                'median_price_tas' => 250.0,
                'median_price_darwin' => 500.0,
                'median_price_nt' => 400.0,
                'median_price_canberra' => 533.0,
            ),
            32 =>
            array(
                'date' => 'Sep-2011',
                'median_price_sydney' => 567.0,
                'median_price_nsw' => 335.0,
                'median_price_melbourne' => 487.0,
                'median_price_vic' => 286.5,
                'median_price_brisbane' => 433.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 390.0,
                'median_price_sa' => 260.0,
                'median_price_perth' => 470.0,
                'median_price_wa' => 375.0,
                'median_price_hobart' => 335.0,
                'median_price_tas' => 250.0,
                'median_price_darwin' => 497.0,
                'median_price_nt' => 397.0,
                'median_price_canberra' => 490.0,
            ),
            33 =>
            array(
                'date' => 'Dec-2011',
                'median_price_sydney' => 533.0,
                'median_price_nsw' => 330.0,
                'median_price_melbourne' => 495.0,
                'median_price_vic' => 290.5,
                'median_price_brisbane' => 430.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 385.0,
                'median_price_sa' => 270.0,
                'median_price_perth' => 480.0,
                'median_price_wa' => 372.5,
                'median_price_hobart' => 337.5,
                'median_price_tas' => 250.0,
                'median_price_darwin' => 515.0,
                'median_price_nt' => 410.0,
                'median_price_canberra' => 500.0,
            ),
            34 =>
            array(
                'date' => 'Mar-2012',
                'median_price_sydney' => 607.5,
                'median_price_nsw' => 345.0,
                'median_price_melbourne' => 478.0,
                'median_price_vic' => 297.5,
                'median_price_brisbane' => 430.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 382.0,
                'median_price_sa' => 270.0,
                'median_price_perth' => 489.5,
                'median_price_wa' => 385.0,
                'median_price_hobart' => 343.0,
                'median_price_tas' => 250.0,
                'median_price_darwin' => 525.0,
                'median_price_nt' => 395.0,
                'median_price_canberra' => 512.5,
            ),
            35 =>
            array(
                'date' => 'Jun-2012',
                'median_price_sydney' => 600.0,
                'median_price_nsw' => 346.0,
                'median_price_melbourne' => 485.0,
                'median_price_vic' => 285.0,
                'median_price_brisbane' => 435.0,
                'median_price_qld' => 375.0,
                'median_price_adelaide' => 385.0,
                'median_price_sa' => 270.0,
                'median_price_perth' => 499.0,
                'median_price_wa' => 375.0,
                'median_price_hobart' => 327.5,
                'median_price_tas' => 247.0,
                'median_price_darwin' => 543.5,
                'median_price_nt' => 392.5,
                'median_price_canberra' => 482.5,
            ),
            36 =>
            array(
                'date' => 'Sep-2012',
                'median_price_sydney' => 585.0,
                'median_price_nsw' => 335.0,
                'median_price_melbourne' => 480.0,
                'median_price_vic' => 290.0,
                'median_price_brisbane' => 435.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 386.0,
                'median_price_sa' => 265.0,
                'median_price_perth' => 495.0,
                'median_price_wa' => 380.0,
                'median_price_hobart' => 315.0,
                'median_price_tas' => 249.0,
                'median_price_darwin' => 540.0,
                'median_price_nt' => 385.5,
                'median_price_canberra' => 490.0,
            ),
            37 =>
            array(
                'date' => 'Dec-2012',
                'median_price_sydney' => 640.0,
                'median_price_nsw' => 360.0,
                'median_price_melbourne' => 508.0,
                'median_price_vic' => 291.5,
                'median_price_brisbane' => 440.0,
                'median_price_qld' => 380.0,
                'median_price_adelaide' => 395.0,
                'median_price_sa' => 250.0,
                'median_price_perth' => 510.0,
                'median_price_wa' => 370.0,
                'median_price_hobart' => 331.3,
                'median_price_tas' => 252.3,
                'median_price_darwin' => 561.0,
                'median_price_nt' => 428.0,
                'median_price_canberra' => 519.0,
            ),
            38 =>
            array(
                'date' => 'Mar-2013',
                'median_price_sydney' => 615.0,
                'median_price_nsw' => 357.5,
                'median_price_melbourne' => 486.0,
                'median_price_vic' => 298.0,
                'median_price_brisbane' => 440.0,
                'median_price_qld' => 390.0,
                'median_price_adelaide' => 395.0,
                'median_price_sa' => 247.5,
                'median_price_perth' => 520.0,
                'median_price_wa' => 380.5,
                'median_price_hobart' => 340.0,
                'median_price_tas' => 250.0,
                'median_price_darwin' => 530.0,
                'median_price_nt' => 415.0,
                'median_price_canberra' => 505.0,
            ),
            39 =>
            array(
                'date' => 'Jun-2013',
                'median_price_sydney' => 650.0,
                'median_price_nsw' => 355.0,
                'median_price_melbourne' => 500.0,
                'median_price_vic' => 282.5,
                'median_price_brisbane' => 445.0,
                'median_price_qld' => 385.5,
                'median_price_adelaide' => 395.0,
                'median_price_sa' => 255.0,
                'median_price_perth' => 529.0,
                'median_price_wa' => 380.0,
                'median_price_hobart' => 330.0,
                'median_price_tas' => 255.0,
                'median_price_darwin' => 540.0,
                'median_price_nt' => 388.0,
                'median_price_canberra' => 510.0,
            ),
            40 =>
            array(
                'date' => 'Sep-2013',
                'median_price_sydney' => 670.0,
                'median_price_nsw' => 350.0,
                'median_price_melbourne' => 520.0,
                'median_price_vic' => 298.0,
                'median_price_brisbane' => 449.0,
                'median_price_qld' => 386.3,
                'median_price_adelaide' => 395.0,
                'median_price_sa' => 253.0,
                'median_price_perth' => 520.0,
                'median_price_wa' => 375.0,
                'median_price_hobart' => 325.0,
                'median_price_tas' => 249.5,
                'median_price_darwin' => 570.0,
                'median_price_nt' => 389.9,
                'median_price_canberra' => 505.0,
            ),
            41 =>
            array(
                'date' => 'Dec-2013',
                'median_price_sydney' => 745.0,
                'median_price_nsw' => 370.0,
                'median_price_melbourne' => 561.0,
                'median_price_vic' => 308.0,
                'median_price_brisbane' => 465.0,
                'median_price_qld' => 395.0,
                'median_price_adelaide' => 412.0,
                'median_price_sa' => 268.3,
                'median_price_perth' => 552.0,
                'median_price_wa' => 385.0,
                'median_price_hobart' => 350.0,
                'median_price_tas' => 250.0,
                'median_price_darwin' => 579.0,
                'median_price_nt' => 424.0,
                'median_price_canberra' => 503.3,
            ),
            42 =>
            array(
                'date' => 'Mar-2014',
                'median_price_sydney' => 680.0,
                'median_price_nsw' => 362.0,
                'median_price_melbourne' => 504.0,
                'median_price_vic' => 290.0,
                'median_price_brisbane' => 448.0,
                'median_price_qld' => 390.0,
                'median_price_adelaide' => 407.0,
                'median_price_sa' => 265.0,
                'median_price_perth' => 530.5,
                'median_price_wa' => 379.0,
                'median_price_hobart' => 360.0,
                'median_price_tas' => 247.0,
                'median_price_darwin' => 595.0,
                'median_price_nt' => 412.5,
                'median_price_canberra' => 553.7,
            ),
            43 =>
            array(
                'date' => 'Jun-2014',
                'median_price_sydney' => 728.0,
                'median_price_nsw' => 368.0,
                'median_price_melbourne' => 528.9,
                'median_price_vic' => 286.0,
                'median_price_brisbane' => 459.0,
                'median_price_qld' => 390.0,
                'median_price_adelaide' => 405.0,
                'median_price_sa' => 250.0,
                'median_price_perth' => 525.0,
                'median_price_wa' => 366.0,
                'median_price_hobart' => 340.0,
                'median_price_tas' => 236.3,
                'median_price_darwin' => 557.5,
                'median_price_nt' => 420.0,
                'median_price_canberra' => 550.0,
            ),
            44 =>
            array(
                'date' => 'Sep-2014',
                'median_price_sydney' => 730.0,
                'median_price_nsw' => 368.6,
                'median_price_melbourne' => 505.0,
                'median_price_vic' => 280.0,
                'median_price_brisbane' => 451.0,
                'median_price_qld' => 390.0,
                'median_price_adelaide' => 410.0,
                'median_price_sa' => 255.0,
                'median_price_perth' => 530.0,
                'median_price_wa' => 370.0,
                'median_price_hobart' => 345.0,
                'median_price_tas' => 262.5,
                'median_price_darwin' => 570.0,
                'median_price_nt' => 439.0,
                'median_price_canberra' => 554.0,
            ),
            45 =>
            array(
                'date' => 'Dec-2014',
                'median_price_sydney' => 816.0,
                'median_price_nsw' => 380.0,
                'median_price_melbourne' => 552.5,
                'median_price_vic' => 298.0,
                'median_price_brisbane' => 467.0,
                'median_price_qld' => 405.0,
                'median_price_adelaide' => 425.0,
                'median_price_sa' => 275.0,
                'median_price_perth' => 531.0,
                'median_price_wa' => 380.0,
                'median_price_hobart' => 356.5,
                'median_price_tas' => 253.5,
                'median_price_darwin' => 581.0,
                'median_price_nt' => 420.0,
                'median_price_canberra' => 570.0,
            ),
            46 =>
            array(
                'date' => 'Mar-2015',
                'median_price_sydney' => 792.5,
                'median_price_nsw' => 390.0,
                'median_price_melbourne' => 525.0,
                'median_price_vic' => 299.0,
                'median_price_brisbane' => 462.8,
                'median_price_qld' => 410.0,
                'median_price_adelaide' => 415.5,
                'median_price_sa' => 265.0,
                'median_price_perth' => 536.5,
                'median_price_wa' => 370.0,
                'median_price_hobart' => 360.0,
                'median_price_tas' => 255.0,
                'median_price_darwin' => 570.0,
                'median_price_nt' => 430.0,
                'median_price_canberra' => 585.0,
            ),
            47 =>
            array(
                'date' => 'Jun-2015',
                'median_price_sydney' => 860.0,
                'median_price_nsw' => 395.0,
                'median_price_melbourne' => 561.0,
                'median_price_vic' => 295.0,
                'median_price_brisbane' => 465.0,
                'median_price_qld' => 410.3,
                'median_price_adelaide' => 420.0,
                'median_price_sa' => 260.0,
                'median_price_perth' => 537.0,
                'median_price_wa' => 355.0,
                'median_price_hobart' => 350.0,
                'median_price_tas' => 252.5,
                'median_price_darwin' => 595.0,
                'median_price_nt' => 450.0,
                'median_price_canberra' => 580.0,
            ),
            48 =>
            array(
                'date' => 'Sep-2015',
                'median_price_sydney' => 888.2,
                'median_price_nsw' => 410.0,
                'median_price_melbourne' => 580.0,
                'median_price_vic' => 295.6,
                'median_price_brisbane' => 475.0,
                'median_price_qld' => 415.0,
                'median_price_adelaide' => 427.5,
                'median_price_sa' => 260.0,
                'median_price_perth' => 520.0,
                'median_price_wa' => 350.0,
                'median_price_hobart' => 340.0,
                'median_price_tas' => 257.5,
                'median_price_darwin' => 580.0,
                'median_price_nt' => 455.0,
                'median_price_canberra' => 587.5,
            ),
            49 =>
            array(
                'date' => 'Dec-2015',
                'median_price_sydney' => 915.0,
                'median_price_nsw' => 412.0,
                'median_price_melbourne' => 612.3,
                'median_price_vic' => 310.0,
                'median_price_brisbane' => 490.0,
                'median_price_qld' => 420.0,
                'median_price_adelaide' => 436.0,
                'median_price_sa' => 273.5,
                'median_price_perth' => 525.0,
                'median_price_wa' => 350.0,
                'median_price_hobart' => 370.0,
                'median_price_tas' => 265.0,
                'median_price_darwin' => 575.0,
                'median_price_nt' => 412.5,
                'median_price_canberra' => 615.0,
            ),
            50 =>
            array(
                'date' => 'Mar-2016',
                'median_price_sydney' => 850.0,
                'median_price_nsw' => 415.0,
                'median_price_melbourne' => 568.0,
                'median_price_vic' => 311.0,
                'median_price_brisbane' => 483.5,
                'median_price_qld' => 425.0,
                'median_price_adelaide' => 436.0,
                'median_price_sa' => 275.0,
                'median_price_perth' => 518.0,
                'median_price_wa' => 360.5,
                'median_price_hobart' => 360.0,
                'median_price_tas' => 264.0,
                'median_price_darwin' => 570.0,
                'median_price_nt' => 472.5,
                'median_price_canberra' => 590.0,
            ),
            51 =>
            array(
                'date' => 'Jun-2016',
                'median_price_sydney' => 895.0,
                'median_price_nsw' => 425.0,
                'median_price_melbourne' => 610.0,
                'median_price_vic' => 305.0,
                'median_price_brisbane' => 495.0,
                'median_price_qld' => 425.0,
                'median_price_adelaide' => 440.0,
                'median_price_sa' => 265.0,
                'median_price_perth' => 520.0,
                'median_price_wa' => 330.0,
                'median_price_hobart' => 365.0,
                'median_price_tas' => 253.0,
                'median_price_darwin' => 548.0,
                'median_price_nt' => 426.0,
                'median_price_canberra' => 623.0,
            ),
            52 =>
            array(
                'date' => 'Sep-2016',
                'median_price_sydney' => 900.0,
                'median_price_nsw' => 430.5,
                'median_price_melbourne' => 605.0,
                'median_price_vic' => 310.0,
                'median_price_brisbane' => 500.0,
                'median_price_qld' => 435.0,
                'median_price_adelaide' => 445.0,
                'median_price_sa' => 270.0,
                'median_price_perth' => 510.0,
                'median_price_wa' => 327.8,
                'median_price_hobart' => 370.0,
                'median_price_tas' => 255.0,
                'median_price_darwin' => 520.0,
                'median_price_nt' => 353.5,
                'median_price_canberra' => 615.8,
            ),
            53 =>
            array(
                'date' => 'Dec-2016',
                'median_price_sydney' => 985.5,
                'median_price_nsw' => 445.0,
                'median_price_melbourne' => 675.0,
                'median_price_vic' => 320.8,
                'median_price_brisbane' => 515.0,
                'median_price_qld' => 439.0,
                'median_price_adelaide' => 447.0,
                'median_price_sa' => 280.0,
                'median_price_perth' => 525.0,
                'median_price_wa' => 345.0,
                'median_price_hobart' => 392.0,
                'median_price_tas' => 274.5,
                'median_price_darwin' => 522.0,
                'median_price_nt' => 454.5,
                'median_price_canberra' => 636.0,
            ),
            54 =>
            array(
                'date' => 'Mar-2017',
                'median_price_sydney' => 930.0,
                'median_price_nsw' => 455.0,
                'median_price_melbourne' => 658.0,
                'median_price_vic' => 328.0,
                'median_price_brisbane' => 510.0,
                'median_price_qld' => 440.0,
                'median_price_adelaide' => 451.3,
                'median_price_sa' => 285.0,
                'median_price_perth' => 510.0,
                'median_price_wa' => 350.0,
                'median_price_hobart' => 389.5,
                'median_price_tas' => 262.8,
                'median_price_darwin' => 530.0,
                'median_price_nt' => 430.1,
                'median_price_canberra' => 655.0,
            ),
            55 =>
            array(
                'date' => 'Jun-2017',
                'median_price_sydney' => 1050.0,
                'median_price_nsw' => 460.0,
                'median_price_melbourne' => 720.0,
                'median_price_vic' => 332.3,
                'median_price_brisbane' => 518.0,
                'median_price_qld' => 449.0,
                'median_price_adelaide' => 450.0,
                'median_price_sa' => 270.0,
                'median_price_perth' => 507.5,
                'median_price_wa' => 327.0,
                'median_price_hobart' => 400.0,
                'median_price_tas' => 275.0,
                'median_price_darwin' => 500.0,
                'median_price_nt' => 423.5,
                'median_price_canberra' => 670.0,
            ),
            56 =>
            array(
                'date' => 'Sep-2017',
                'median_price_sydney' => 950.0,
                'median_price_nsw' => 460.0,
                'median_price_melbourne' => 695.0,
                'median_price_vic' => 328.0,
                'median_price_brisbane' => 525.0,
                'median_price_qld' => 445.0,
                'median_price_adelaide' => 451.0,
                'median_price_sa' => 277.0,
                'median_price_perth' => 502.0,
                'median_price_wa' => 325.0,
                'median_price_hobart' => 395.0,
                'median_price_tas' => 275.0,
                'median_price_darwin' => 500.0,
                'median_price_nt' => 443.0,
                'median_price_canberra' => 667.5,
            ),
            57 =>
            array(
                'date' => 'Dec-2017',
                'median_price_sydney' => 1030.0,
                'median_price_nsw' => 475.0,
                'median_price_melbourne' => 752.0,
                'median_price_vic' => 350.0,
                'median_price_brisbane' => 534.6,
                'median_price_qld' => 450.0,
                'median_price_adelaide' => 470.0,
                'median_price_sa' => 273.7,
                'median_price_perth' => 515.0,
                'median_price_wa' => 342.5,
                'median_price_hobart' => 422.0,
                'median_price_tas' => 285.0,
                'median_price_darwin' => 513.8,
                'median_price_nt' => 437.5,
                'median_price_canberra' => 689.5,
            ),
            58 =>
            array(
                'date' => 'Mar-2018',
                'median_price_sydney' => 960.0,
                'median_price_nsw' => 480.0,
                'median_price_melbourne' => 733.0,
                'median_price_vic' => 357.0,
                'median_price_brisbane' => 525.5,
                'median_price_qld' => 449.0,
                'median_price_adelaide' => 465.0,
                'median_price_sa' => 280.0,
                'median_price_perth' => 510.0,
                'median_price_wa' => 338.0,
                'median_price_hobart' => 450.0,
                'median_price_tas' => 295.0,
                'median_price_darwin' => 490.0,
                'median_price_nt' => 445.0,
                'median_price_canberra' => 698.0,
            ),
            59 =>
            array(
                'date' => 'Jun-2018',
                'median_price_sydney' => 980.0,
                'median_price_nsw' => 485.0,
                'median_price_melbourne' => 750.0,
                'median_price_vic' => 355.0,
                'median_price_brisbane' => 532.0,
                'median_price_qld' => 436.0,
                'median_price_adelaide' => 470.0,
                'median_price_sa' => 275.0,
                'median_price_perth' => 510.0,
                'median_price_wa' => 310.0,
                'median_price_hobart' => 457.8,
                'median_price_tas' => 300.0,
                'median_price_darwin' => 515.0,
                'median_price_nt' => 446.0,
                'median_price_canberra' => 695.0,
            ),
            60 =>
            array(
                'date' => 'Sep-2018',
                'median_price_sydney' => 950.0,
                'median_price_nsw' => 476.0,
                'median_price_melbourne' => 720.0,
                'median_price_vic' => 354.2,
                'median_price_brisbane' => 540.0,
                'median_price_qld' => 440.0,
                'median_price_adelaide' => 466.8,
                'median_price_sa' => 285.0,
                'median_price_perth' => 491.0,
                'median_price_wa' => 327.3,
                'median_price_hobart' => 445.0,
                'median_price_tas' => 292.3,
                'median_price_darwin' => 502.5,
                'median_price_nt' => 420.0,
                'median_price_canberra' => 704.5,
            ),
            61 =>
            array(
                'date' => 'Dec-2018',
                'median_price_sydney' => 940.0,
                'median_price_nsw' => 465.0,
                'median_price_melbourne' => 730.0,
                'median_price_vic' => 370.0,
                'median_price_brisbane' => 540.0,
                'median_price_qld' => 430.0,
                'median_price_adelaide' => 478.0,
                'median_price_sa' => 290.0,
                'median_price_perth' => 490.0,
                'median_price_wa' => 320.2,
                'median_price_hobart' => 460.0,
                'median_price_tas' => 310.0,
                'median_price_darwin' => 510.0,
                'median_price_nt' => 455.0,
                'median_price_canberra' => 720.0,
            ),
            62 =>
            array(
                'date' => 'Mar-2019',
                'median_price_sydney' => 847.0,
                'median_price_nsw' => 460.0,
                'median_price_melbourne' => 655.0,
                'median_price_vic' => 361.1,
                'median_price_brisbane' => 530.0,
                'median_price_qld' => 425.0,
                'median_price_adelaide' => 470.0,
                'median_price_sa' => 285.0,
                'median_price_perth' => 490.0,
                'median_price_wa' => 325.0,
                'median_price_hobart' => 465.2,
                'median_price_tas' => 310.0,
                'median_price_darwin' => 472.5,
                'median_price_nt' => 399.5,
                'median_price_canberra' => 690.0,
            ),
        ));
    }
}
